[request_definition]
# 定义一次权限检查需要哪些参数。
#
# sub = subject
#     谁在操作
#
# obj = object
#     操作什么资源
#
# act = action
#     执行什么动作
r = sub, obj, act


[policy_definition]
# 定义一条权限策略包含什么。
#
# sub = 角色
# obj = 资源
# act = 动作
p = sub, obj, act


[role_definition]
# 定义角色继承关系。
#
# g = user / role
#
# 例如：
#
# admin, super_admin
#
# 表示 admin 继承 super_admin 的权限。
g = _, _


[policy_effect]
# 只有当策略匹配时才允许。
#
# some(where (p.eft == allow))
e = some(where (p.eft == allow))


[matchers]
# 权限判断规则。
#
# g(r.sub, p.sub)
#     ↓
# 当前用户是否属于这个角色
#
# r.obj == p.obj
#     ↓
# 请求资源是否匹配
#
# r.act == p.act
#     ↓
# 请求动作是否匹配
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act